name: MGSHDFix CI Builds

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
      
    - run: msbuild ${{ github.event.repository.name }}.sln -t:rebuild -verbosity:diag -property:Configuration=Release -property:Platform=x64
    - run: mkdir .\dist
    - run: cp x64\Release\${{ github.event.repository.name }}.asi ${{ github.event.repository.name }}.asi

    - uses: robinraju/release-downloader@v1.8
      with:
        repository: "ThirteenAG/Ultimate-ASI-Loader"
        latest: true
        fileName: "Ultimate-ASI-Loader_x64.zip"
    - run: unzip Ultimate-ASI-Loader_x64.zip -d .\dist
    - run: C:\msys64\usr\bin\wget.exe -O .\dist\UltimateASILoader_LICENSE.md https://raw.githubusercontent.com/ThirteenAG/Ultimate-ASI-Loader/master/license 
    - run: cp .\dist\dinput8.dll .\dist\wininet.dll
    - run: mv .\dist\dinput8.dll .\dist\winhttp.dll
    - run: mkdir .\dist\logs
    - run: cp .\README.md .\dist\logs\${{ github.event.repository.name }}.log
    - run: mkdir .\dist\plugins
    - run: mv .\README.md .\dist\plugins\${{ github.event.repository.name }}_README.md
    - run: mv .\${{ github.event.repository.name }}.ini .\dist\plugins\${{ github.event.repository.name }}.ini
    - run: mv .\${{ github.event.repository.name }}.asi .\dist\plugins\${{ github.event.repository.name }}.asi

    - name: Create release zip
      run: |
        7z a -tzip ${{ github.event.repository.name }}-run-${{ github.run_number }}.zip dist\

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-run-${{ github.run_number }}
        path: dist/
